import React, { useContext } from "react";
import "./style.css";
import { store } from "../../context/context";

function Home() {
  const {
    state: { lang },
  } = useContext(store);
  return (
    <section>
      <div className="container">
        <div className="text-div">
          <p className="text">
            {lang === "uz"
              ? "Mebel (lot. mobilis — qoʻzgʻaladigan, osongina suriladigan), jihoz xonalar, istirohat bogʻlari, koʻchalar jihozining asosiy turi.  Maishiy (uy-roʻzgʻorda ishlatiladigan), jamoat bi-nolari va joylari (bogʻchayasli, maktab, oʻquv yurtlari, idoralar, teatr, klub, kinoteatr, doʻkonlar, kafe va restoranlar, sanoat binolari va boshqalar) da qoʻllaniladigan xillarga boʻlinadi. M. (kursi, xontaxta, javon, belanchak, beshik, stul, stol, shkaf, karavot, divan, sandiq, kuti, skameyka, parta va boshqalar) insonning mehnati — mashgʻuloti, dam olishini qulaylashtirish uchun xizmat qiladi. Yogʻochning qattiq turlari (eman, shamshod, yongʻoq, nok, qayin, lipa, tol, terak, kizil daraxt, chinor, qayragʻoch, olxa, shumtol, archa, qaragʻay, tilogʻoch va boshqalar), metall va pla-stmassadan ishlanadi, novdalardan toʻqiladi. Vazifasi, tuzilishi, materialiga qarab juda koʻp turlarga boʻlinadi, har bir turining ham bir necha xili boʻladi (mas, stolning ovqat tay-yorlash va ovqatlanishda ishlatiladigan, yozuv stoli kabi xillari, javonning kitob terib qoʻyiladigan, korxonada — asbob-uskunalar saqlanadiganxillari bor). Maishiy (uy-roʻzgʻor) da ishlatiladigan M. yotoqxona, mehmonxona, oshxona va hovli M.lari kabi xillarga boʻlinadi. Bir xonali uylarga moʻljallab ishlab chiqariladigan M.lar ham yotokxona, ham mehmonxona M.i vazifasini oʻtaydi (mas, divankaravot, kreslokaravot). Ikki, baʼzan undan ortiq turi birlashtirilgan M.lar ham ishlab chikariladi. Tuzilishi va texnologik jihatlariga koʻra, M. joyidan qoʻzgʻalmaydigan va qoʻzgʻaladigan, yigʻma, devorga oʻrnatiladigan va boshqa xillarga boʻlinadi. M. xonani, bino ichini badiiy bezash uchun xizmat qiladi, amaliy sanʼat sohasi ham hisoblanadi (M.larni bezashda rassomlik, haykaltaroshlik va naqshdan foydalaniladi)."
              : lang === "ru"
              ? " Мебель (лат. mobilis — подвижный, легко перемещаемый), оборудование —помещения, парки отдыха, основной вид уличного оборудования.Жилые (хозяйственные), общественные здания и места(детские сады, школы, учебные заведения, офисы, театры, клубы,кинотеатр, магазины, кафе и рестораны, промышленные здания и и т. д.) делятся на типы, используемые в М. (конечно,кровать, полка, качели, колыбель, стул, стол, шкаф, кровать, диван, сундук, тахта, скамейка, письменный стол и т. д.) человеческий труд— служит для облегчения тренировок и отдыха. Твердые породы древесины (дуб, самшит, орех, груша, береза, липа, ива, тополь, красное дерево, клен, лиственница, бук,ель, сосна, тилогоч и др.), металл и пластик. он выработан, сплетен из ветвей. Задача, структура, материал Он разделен на множество типов, каждый тип имеет несколько различен (например, в приготовлении и употреблении за столом используемый, например, письменный стол, книжная полка есть виды, где оборудование хранится на предприятии). М. используется в бытовой (домашней) спальне, гостинице, делятся на такие типы, как кухонные и дворовые М. В однокомнатные дома Номера спроектированы как для общежития, так и для гостиницы. Служит кроватью (например, диван-кровать, кресло-кровать). два, иногда сочетается более одного типа М. выпущен. По своей структуре и технологическим аспектам он происходит от места М. стационарные и передвижные, складные, настенные и делится на другие виды. м. художественное оформление помещения, интерьер здания служит для, также считается областью прикладного искусства (М. в декоре используются живопись, скульптура и узор)."
              : "Furniture (lat. mobilis - movable, easily moved), equipment - rooms, recreation parks, the main type of street equipment. Domestic (household), public buildings and places (kindergartens, schools, educational institutions, offices, theaters, clubs, cinema, shops, cafes and restaurants, industrial buildings and etc.) are divided into types used in M. (course, bed, shelf, swing, cradle, chair, table, wardrobe, bed, sofa, chest, couch, bench, desk, etc.) human labor — serves to facilitate training and rest. Hard types of wood (oak, boxwood, walnut, pear, birch, linden, willow, poplar, redwood, maple, larch, beech, fir, pine, tilogoch, etc.), metal and plastic it is worked, woven from branches. Task, structure, material It is divided into many types, each type has several is different (for example, in preparing and eating at the table used, such as a writing desk, a bookshelf there are types where equipment is stored at the enterprise). M. used in household (household) bedroom, hotel, are divided into such types as kitchen and yard M. To one-room houses The rooms are designed for both a dormitory and a hotel Serves as a bed (for example, sofa bed, armchair bed). two, sometimes more than one type of M. is combined is released. According to its structure and technological aspects, it is from the place of M fixed and movable, collapsible, wall-mounted and is divided into other types. M. artistic decoration of the room, the interior of the building serves for, is also considered a field of applied art (M painting, sculpture and pattern are used in decoration)."}
          </p>
        </div>
      </div>
    </section>
  );
}

export default Home;
